### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by israellevin** [nogalavi/TransferMoney#1]
After issuing `python manage.py runserver` I get a bunch of errors indicating that Django is not installed. It would be better to have a `requirements.txt` file with instructions in the README.

After a quick `pip install django` I get the following error:
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/root/noga/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/root/noga/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/root/noga/env/lib/python3.5/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/root/noga/env/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/noga/env/lib/python3.5/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'TransferMoneyServer.settings'
```

And, indeed, there is no `TransferMoneyServer/settings.py`.

After creating it, and setting debug to True and adding a secret key I managed to run the server, but then it complained about `ROOT_URLCONF` so I gave up.

**Comment by nogashimoni** [comment]
Sorry about that, let me take some time to repackage it. I'll send you an
email once its ready.
Noga

On 25 Dec 2016 11:49 am, "israellevin" <notifications@github.com> wrote:

After issuing python manage.py runserver I get a bunch of errors indicating
that Django is not installed. It would be better to have a requirements.txt
file with instructions in the README.

After a quick pip install django I get the following error:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/root/noga/env/lib/python3.5/site-packages/django/core/management/__init__.py",
line 367, in execute_from_command_line
    utility.execute()
  File "/root/noga/env/lib/python3.5/site-packages/django/core/management/__init__.py",
line 316, in execute
    settings.INSTALLED_APPS
  File "/root/noga/env/lib/python3.5/site-packages/django/conf/__init__.py",
line 53, in __getattr__
    self._setup(name)
  File "/root/noga/env/lib/python3.5/site-packages/django/conf/__init__.py",
line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/noga/env/lib/python3.5/site-packages/django/conf/__init__.py",
line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'TransferMoneyServer.settings'

And, indeed, there is no TransferMoneyServer/settings.py.

After creating it, and setting debug to True and adding a secret key I
managed to run the server, but then it complained about ROOT_URLCONF so I
gave up.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nogalavi/TransferMoney/issues/1>, or mute the thread

**Comment by nogashimoni** [comment]
This is supposed to work now. Please let me know if there are further issues
